### ISSUE TITLE
Question about model performance

### ISSUE THREAD

**Issue by FantasyJXF** [lizhengwei1992/Semantic_Human_Matting#19]
Thanks for your nice work.

I trained your model with aisegment dataset, during the test time, there are always white block on the foreground like this
![下载](https://user-images.githubusercontent.com/16235526/62262815-a6c5b600-b44c-11e9-9ba0-9b363f39ab2c.png)

And I test with your pretrained model, it also have same problem

![mask1](https://user-images.githubusercontent.com/16235526/62262751-70883680-b44c-11e9-92a7-7af8c04ae8fc.png)

Looking forward to your reply....

**Comment by Jason-xin** [comment]
When I run ./test_camera.sh (--without_gpu), this error occurred:
AttributeError: Can't get attribute 'RD_FPNnet' on <module 'model.T_Net' from '/Users/jasonxin/Documents/dlworkspace/Semantic_Human_Matting/model/T_Net.py'>
My torch version is 1.0.0.

**Comment by hassanrazakhalid** [comment]
yes i am also getting the same issue on pretrained model. I have not tried my own model yet. Please see image below
https://ibb.co/rQ0xMzd. If some has any solution please share or if some one has achieved better results

**Comment by FantasyJXF** [comment]
> yes i am also getting the same issue on pretrained model. I have not tried my own model yet. Please see image below
> https://ibb.co/rQ0xMzd. If some has any solution please share or if some one has achieved better results

if you use numpy, just clip the value to [0,255] and use dtype np.uint8 would solve the problem.

The model really need good datasets which was so so hard to get

**Comment by hassanrazakhalid** [comment]
yes but this only remove white and black, what about greenish background which is merged as foreground

**Comment by FantasyJXF** [comment]
That's because the pretrained model was not good enough. That's what you could improve.

The picture you provided has green background, did it?

Have you try https://www.remove.bg/?

**Comment by hassanrazakhalid** [comment]
First link is from remove.bg
https://ibb.co/FzKFyx1
This is from your algo and provided model.
https://ibb.co/RNyRnxb

The results of remove.bg are very good.
1.  Are they using the same approach that is used in this. 
2. Also as you suggested to improve model. I just need a good data set or i need to change the trainning model as well.
3. For dataset Is the following dataset good enough
https://www.kaggle.com/laurentmih/aisegmentcom-matting-human-datasets
