### ISSUE TITLE
Predict alpha result

### ISSUE THREAD

**Issue by Jason-xin** [lizhengwei1992/Semantic_Human_Matting#22]
After trained, I got alpha results like this:
![image](https://user-images.githubusercontent.com/13817995/63261875-1940ed80-c2b7-11e9-8fb7-ff2479bd8456.png)

Then, Is this correct alpha result? And, how can I get the final result like this:
![image](https://user-images.githubusercontent.com/13817995/63261933-44c3d800-c2b7-11e9-8415-2bcb52a4d1f8.png)

**Comment by xiankgx** [comment]
Alpha result should be in the range of 0 to 1, or 0 to 255. You seemed to have trained the model to convert from color to grayscale. Note that grayscale is not alpha.
