### ISSUE TITLE
Alpha image is gray, how to np2Tensor?

### ISSUE THREAD

**Issue by Jason-xin** [lizhengwei1992/Semantic_Human_Matting#23]
Hello, in code datase.py
`def np2Tensor(array):
    ts = (2, 0, 1)
    tensor = torch.FloatTensor(array.transpose(ts).astype(float))    
    return tensor`
but alpha image is gray with only 2-D, how to transpose it?

**Comment by xiankgx** [comment]
> Hello, in code datase.py
> `def np2Tensor(array): ts = (2, 0, 1) tensor = torch.FloatTensor(array.transpose(ts).astype(float)) return tensor`
> but alpha image is gray with only 2-D, how to transpose it?

Stack 3 copies of the same rank-2 grayscale image tensor to become a rank-3 tensor.
