### ISSUE TITLE
'AvgPool2d' object has no attribute 'divisor_override'

### ISSUE THREAD

**Issue by chdzhen** [lizhengwei1992/Semantic_Human_Matting#24]
hi, thank you for your code.
but when I run test_camera.sh this error 'AvgPool2d' object has no attribute 'divisor_override' appear, my env is  torch-1.2.0+cpu、torchvision-0.4.0+cpu、python3.6.3. 
who can help me ?
thanks again!

**Comment by chdzhen** [comment]
in T_Net.py change this:
        input_cascade1 = nn.AvgPool2d(3, stride=2, padding=1)(input)
        input_cascade2 = nn.AvgPool2d(3, stride=2, padding=1)(input_cascade1)
        input_cascade3 = nn.AvgPool2d(3, stride=2, padding=1)(input_cascade2)
        input_cascade4 = nn.AvgPool2d(3, stride=2, padding=1)(input_cascade3)

        # input_cascade1 = self.cascade(input)
        # input_cascade2 = self.cascade(input_cascade1)
        # input_cascade3 = self.cascade(input_cascade2)
        # input_cascade4 = self.cascade(input_cascade3)

**Comment by gravitychen** [comment]
I think you can re-define the avgpool2d.
1. print(your_net) to get the parameter
and I got 
` (avgpool): AvgPool2d(kernel_size=7, stride=1, padding=0)
    (fc): Linear(in_features=512, out_features=512, bias=True)`

2.re-define this layer
model = torch.load(your_model_path)
model.avgpool = nn.AvgPool2d(kernel_size=7, stride=1, padding=0)

**Comment by watertianyi** [comment]
> input_cascade1 = nn.AvgPool2d(3, stride=2, padding=1)(input)
> input_cascade2 = nn.AvgPool2d(3, stride=2, padding=1)(input_cascade1)
> input_cascade3 = nn.AvgPool2d (3, stride=2, padding=1)(input_cascade2)
> input_cascade4 = nn.AvgPool2d(3, stride=2, padding=1)(input_cascade3)

AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'

**Comment by kakumarabhishek** [comment]
I am not using this repository, but this error popped up in a different project, and your solution worked for me @gravitychen. Thank you.
