### ISSUE TITLE
Can you provide a pretrained model ?

### ISSUE THREAD

**Issue by GuideWsp** [lizhengwei1992/Semantic_Human_Matting#4]
RT.

**Comment by farazBhatti** [comment]
Great work by the way @lizhengwei1992 . Is there any chance to have a pretrained model for testing...?

**Comment by lan2720** [comment]
+1

**Comment by lizhengwei1992** [comment]
@GuideWsp @lan2720  see the branch fast_human_matting !

**Comment by lan2720** [comment]
@lizhengwei1992 Thank you! It works.

**Comment by farazBhatti** [comment]
@lan2720 can you please share the link of pretrained model? i can't find fast_human_matting..

**Comment by lan2720** [comment]
@farazBhatti https://github.com/lizhengwei1992/Semantic_Human_Matting/tree/fast_human_matting

**Comment by Jason-xin** [comment]
> @farazBhatti https://github.com/lizhengwei1992/Semantic_Human_Matting/tree/fast_human_matting

@farazBhatti @lizhengwei1992 When I run ./test_camera.sh (--without_gpu), this error occurred:
AttributeError: Can't get attribute 'RD_FPNnet' on <module 'model.T_Net' from '/Users/jasonxin/Documents/dlworkspace/Semantic_Human_Matting/model/T_Net.py'>
