### ISSUE TITLE
Ask about dataset question.

### ISSUE THREAD

**Issue by st931630** [lizhengwei1992/Semantic_Human_Matting#5]
I used the dataset from "Automatic Portrait Segmentation for Image Stylization".
I have run this dataset preprocessing data but I don't see mask image from that.
How can I do to get mask images(.png) from this dataset?

**Comment by tsing90** [comment]
refer to 'gen_trimap.py' in ./data

**Comment by st931630** [comment]
> refer to 'gen_trimap.py' in ./data

Thank you for your relay.
I check 'gen_trimap.py' that has to read mask image from ./data/mask and generates trimap data.
However, I don't know how to generate mask image(.png).
Please correct me if I am wrong.

**Comment by tsing90** [comment]
mask images should be provided by datasets as described in that paper. however, as the repo holder mentioned, you can either use segmentation data as masks (like coco) or gather alpha matting images from other datasets (like the one used in "deep image matting")

**Comment by st931630** [comment]
I understood my question and solved it.
The dataset 'images_mask' folder contains all mask raw data (xxx.mat) so I can generate mask image(.png) from those.
Thank you for your suggestion. It is also helpful to me.
